### ISSUE TITLE
Creating new categories

### ISSUE THREAD

**Issue by Luisibear98** [Telefonica/gymnos#187]
When creating a new model which does not correspond to an already existing domain it throws the following:

> Error: Invalid value for 'DOMAIN': Main domain must be one of the following: vision, generative, audio, nlp, rl, tabular

Command executed: 
 `gymnos-create model tiny_autoencoder unsupervised/anomaly_detection`

How can I add new Domains?

cheers! :D

**Comment by r-salas** [comment]
Anomaly detection is usually used on tabular datasets, maybe `tabular/anomaly_detection`?

**Comment by Luisibear98** [comment]
I will go for that! thanks!
