### ISSUE TITLE
Dependencies by experiment

### ISSUE THREAD

**Issue by kawaits** [Telefonica/gymnos#77]
It might be useful to inject dependencies to a Dockerfile and have these dependencies defined for each experiment. Different points of view:

1.- General docker image for develoment purposes
2.- To generate a specific Docker for a whole model life cycle, even for prediction
3.- To have a base Dockerfile with basic dependencies and tune it up for experiment dependencies

**Comment by r-salas** [comment]
Solved with lazy imports #111 .  We have basic dependencies and extra dependencies can be installed automatically. If you want to create a Dockerfile for a specific experiment, just install the extra dependencies.
