### ISSUE TITLE
LibraryDataset read() method unnecessary declared

### ISSUE THREAD

**Issue by kawaits** [Telefonica/gymnos#82]
read() method seems to be unnecesary since LibraryDataset inherits from Dataset:

class LibraryDataset(Dataset):

    """
    Parent class for all datasets available with a library e.g Keras, Scikit-Learn, NLTK, etc ...
    Must implement:
        - read(download_dir)
    """

    def read(self, download_dir=None):
        raise NotImplementedError()

**Comment by r-salas** [comment]
Read method is the method where you return the data from the library, the download method is the one that is not necessary

**Comment by kawaits** [comment]
Please document the class method accordingly:

    def read(self, download_dir=None):
        ''' bla, bla
        '''
        raise NotImplementedError()
