### ISSUE TITLE
Gymnos Pool: execution environment selection via config

### ISSUE THREAD

**Issue by kawaits** [Telefonica/gymnos#93]
Infrastructure must be offered as a set of HW profiles via configuration file:

```json
"execution_env":{
    "profile": "HW_1"
}
```

**Comment by kawaits** [comment]
Low cost: 
 - Infrastructure must be offered as a set of HW profiles via configuration file:

"execution_env":{
    "profile": "HW_1"
}

Medium:
 - Gymnos must provide a mechanism to infer the most suitable HW profile to run the experiment

**Comment by r-salas** [comment]
Merged branch for distributed datasets (#132) implements execution environment for 4th platform but is generic for any execution environment. @kawaits, can we close this issue?

**Comment by kawaits** [comment]
No longer related to Gymnos. Handled as part of SOFIA BE architecture
